version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: finanzas_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: finanzas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - finanzas_network

  # Adminer para administrar la base de datos (opcional)
  adminer:
    image: adminer:latest
    container_name: finanzas_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - finanzas_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  finanzas_network:
    driver: bridge
